### PR TITLE
Use correct separator in keywords.txt

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE requires the use of a tab separator between the name and identifier. Without this tab the keyword is not highlighted.

Reference: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords

### CODE REVIEW

**Comment by suculent** [comment]
Fixed.

**Comment by per1234** [comment]
LOL you should have just clicked the merge button instead of attempting to duplicate my work. You ended up [changing all the tabs to spaces](https://github.com/suculent/thinx-lib-esp8266-arduinoc/commit/355994c26440d49c5b1bb25e5e3d292695a260f1#diff-70226ca47d4a322249c63d5e716579cc) and thus breaking highlighting for all keywords.

**Comment by suculent** [comment]
LOL! :o))) Sorry I didn’t even notice... However those keywords will need a review anyway, this is just a draft from before the library even started working. 

Odesláno z iPhonu

20. 2. 2018 v 8:10, per1234 <notifications@github.com>:

**Comment by suculent** [comment]
It was caused by lint in Atom text editor, automatically converting tabs to spaces. Aargh, too smart.

**Comment by per1234** [comment]
Yeah, I figured that was the case. I always use spaces instead of tabs so it's a struggle to make sure I put true tabs in keywords.txt. There's actually some work being done now to make the Arduino IDE support spaces in keywords.txt but I'm not sure whether it's going to end up happening and if so how long it will take. Even if it does that will only affect future IDE versions so it's still best to use tabs for backwards compatibility with previous IDE versions.

**Pull request closed without merging**
